<?php

namespace Roots\Sage\Setup;

use Roots\Sage\Assets;

/**
 * Theme setup
 */
function setup() {
  // Enable features from Soil when plugin is activated
  // https://roots.io/plugins/soil/
  add_theme_support('soil-clean-up');
  add_theme_support('soil-nav-walker');
  add_theme_support('soil-nice-search');
  add_theme_support('soil-jquery-cdn');
  add_theme_support('soil-relative-urls');

  // Make theme available for translation
  // Community translations can be found at https://github.com/roots/sage-translations
  load_theme_textdomain('sage', get_template_directory() . '/lang');

  // Enable plugins to manage the document title
  // http://codex.wordpress.org/Function_Reference/add_theme_support#Title_Tag
  add_theme_support('title-tag');

  // Register wp_nav_menu() menus
  // http://codex.wordpress.org/Function_Reference/register_nav_menus
  register_nav_menus([
    'primary_navigation' => __('Primary Navigation', 'sage')
  ]);

  // Enable post thumbnails
  // http://codex.wordpress.org/Post_Thumbnails
  // http://codex.wordpress.org/Function_Reference/set_post_thumbnail_size
  // http://codex.wordpress.org/Function_Reference/add_image_size
  add_theme_support('post-thumbnails');

  // Enable post formats
  // http://codex.wordpress.org/Post_Formats
  add_theme_support('post-formats', ['aside', 'gallery', 'link', 'image', 'quote', 'video', 'audio']);

  // Enable HTML5 markup support
  // http://codex.wordpress.org/Function_Reference/add_theme_support#HTML5
  add_theme_support('html5', ['caption', 'comment-form', 'comment-list', 'gallery', 'search-form']);

  // Use main stylesheet for visual editor
  // To add custom styles edit /assets/styles/layouts/_tinymce.scss
  add_editor_style(Assets\asset_path('styles/main.css'));
}
add_action('after_setup_theme', __NAMESPACE__ . '\\setup');

/**
 * Register sidebars
 */
function widgets_init() {
  register_sidebar([
    'name'          => __('Primary', 'sage'),
    'id'            => 'sidebar-primary',
    'before_widget' => '<section class="widget %1$s %2$s">',
    'after_widget'  => '</section>',
    'before_title'  => '<h3>',
    'after_title'   => '</h3>'
  ]);

  register_sidebar([
    'name'          => __('Footer', 'sage'),
    'id'            => 'sidebar-footer',
    'before_widget' => '<section class="widget %1$s %2$s">',
    'after_widget'  => '</section>',
    'before_title'  => '<h3>',
    'after_title'   => '</h3>'
  ]);
}
add_action('widgets_init', __NAMESPACE__ . '\\widgets_init');

/**
 * Determine which pages should NOT display the sidebar
 */
function display_sidebar() {
  static $display;

  isset($display) || $display = !in_array(true, [
    // The sidebar will NOT be displayed if ANY of the following return true.
    // @link https://codex.wordpress.org/Conditional_Tags
    is_404(),
    is_front_page(),
    is_page_template('template-custom.php'),
  ]);

  return apply_filters('sage/display_sidebar', $display);
}

/**
 * Theme assets
 */
function assets() {
  if (is_child_theme()) {
    wp_enqueue_style('sage/base-css', get_template_directory_uri() . '/style.css', false, null);
  } else {
    wp_enqueue_style('sage/css', Assets\asset_path('styles/main.css'), false, null);
  }

  if (is_single() && comments_open() && get_option('thread_comments')) {
    wp_enqueue_script('comment-reply');
  }

  wp_enqueue_script('sage/js', Assets\asset_path('scripts/main.js'), ['jquery'], null, true);
}
add_action('wp_enqueue_scripts', __NAMESPACE__ . '\\assets', 1000);

function assets_high_priotiy() {
  wp_enqueue_script('sage/customizer-js', Assets\asset_path('scripts/customizer.js'), ['jquery'], null, true);
}
add_action('wp_enqueue_scripts', __NAMESPACE__ . '\\assets_high_priotiy', 1);

function get_author_text_credit() {
  return <<<TEXT
             This website was developed by Ngoc L.B.
          Feel free to touch me at <contact@ngoclb.com>
                                  .
/////////////////////////////////////////////////////////////////////////
                                _   _
                               | | | |
 _ __     __ _    ___     ___  | | | |__         ___    ___    _ __ ___
| '_ \   / _` |  / _ \   / __| | | | '_ \       / __|  / _ \  | '_ ` _ \
| | | | | (_| | | (_) | | (__  | | | |_) |  _  | (__  | (_) | | | | | | |
|_| |_|  \__, |  \___/   \___| |_| |_.__/  (_)  \___|  \___/  |_| |_| |_|
          __/ |
         |___/
/////////////////////////////////////////////////////////////////////////
TEXT;
}
/**
 * Print some HTML code before body tag
 *
 * @return void
 */
function html_on_before_tag() {
  // We need put child css file here to override custom style generated by parent theme
  if (is_child_theme()) {
    echo sprintf("<link rel='stylesheet' href='%s' type='text/css' media='all' />\n", Assets\asset_path('styles/main.css'));
  }
  echo "<script id='author-credit'>//<![CDATA[\n";
  $credit = explode("\n", get_author_text_credit());
  array_walk($credit, function($text) {
    echo sprintf("console.log(\"%s\", \"%s\");", '%c' . str_replace("\\", "\\\\", $text), "color: red; font-size: 16px; font-weight: bold; text-shadow: 0 1px 0 #ccc, 0 2px 0 #c9c9c9, 0 3px 0 #bbb, 0 4px 0 #b9b9b9, 0 5px 0 #aaa, 0 6px 1px rgba(0,0,0,.1), 0 0 5px rgba(0,0,0,.1), 0 1px 3px rgba(0,0,0,.3), 0 3px 5px rgba(0,0,0,.2), 0 5px 10px rgba(0,0,0,.25), 0 1px 1px rgba(0,0,0,.2), 0 2px 2px rgba(0,0,0,.15);");
  });
  echo "\n//]]></script>";
}
add_action('wp_head', __NAMESPACE__ . '\\html_on_before_tag', 10000);
add_action('wp_head', function() {
  echo "<meta name=\"web_author\" content=\"Ngoc L.B <contact@ngoclb.com>\" />\n";
}, 1);

