version: "3"
services:
  traefik:
    image: traefik
    restart: unless-stopped
    command: -c /dev/null --web --docker --logLevel=DEBUG
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mailhog:
    restart: unless-stopped
    image: mailhog/mailhog
    labels:
      - "traefik.backend=mailhog"
      - "traefik.port=8025"
      - "traefik.frontend.rule=Host:mailhog.${WPSITE_URL}"
      - "traefik.frontend.entryPoints=http"

  adminer:
    image: adminer
    restart: unless-stopped
    labels:
      - "traefik.backend=adminer"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:adminer.${WPSITE_URL}"
      - "traefik.frontend.entryPoints=http"

  db:
    image: ${DB_IMAGE}
    restart: unless-stopped
    labels:
      - "traefik.enable=false"
    volumes:
      - ".data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

networks:
  default:
    internal: true
