version: "3"
services:

  php:
    restart: unless-stopped
    container_name: ${WPSITE_URL}_wordpress
    image: wodby/wordpress:${WORDPRESS_TAG}
    volumes:
      - ./src:/var/www/src
      - ./www:/var/www/html
    labels:
      - "traefik.enable=false"
    env_file:
      - ".env"

  apache:
    restart: unless-stopped
    container_name: ${WPSITE_URL}_server
    image: wodby/apache:${APACHE_TAG}
    depends_on:
      - php
    environment:
      APACHE_LOG_LEVEL: debug
      APACHE_BACKEND_HOST: ${WPSITE_URL}_wordpress
      APACHE_VHOST_PRESET: php
    volumes:
      - ./src:/var/www/src
      - ./www:/var/www/html
    labels:
      - "traefik.backend=${WPSITE_URL}"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:${WPSITE_URL}"

# Start traefik proxy first (https://github.com/lbngoc/devbox)
# then change devbox_reverse_proxy to correct your network name
networks:
  default:
    external:
      name: devbox_reverse_proxy
